### ISSUE TITLE
AffID is printing out in hex

### ISSUE THREAD

**Issue by hexlax** [vrtadmin/locky#2]
The Affiliate ID is being printed to stdout with the hex value, not the actual decimal value for the affiliate:

Line 609 in Locky_Dump_main.c
`
printf("affilID: %X\n", ConfigStart->affilID);
`

**Comment by SecsAndCyber** [comment]
The hex value is how we are tracking samples internally.

**Comment by hexlax** [comment]
Roger that - thanks for getting back to me.
